(:~
 : This module contains some basic examples for RESTXQ annotations
 : @author BaseX Team
 :)
module namespace page = 'http://basex.org/modules/web-page';
declare option db:writeback 'true';


(:~
 : This function generates the welcome page.
 : @return HTML page
 :)
declare
  %rest:path("")
  %output:method("xhtml")
  %output:omit-xml-declaration("no")
  %output:doctype-public("-//W3C//DTD XHTML 1.0 Transitional//EN")
  %output:doctype-system("http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd")
  function page:start()
  as element(Q{http://www.w3.org/1999/xhtml}html)
{
  <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <title>BaseX HTTP Services</title>
      <link rel="stylesheet" type="text/css" href="static/style.css"/>
    </head>
    <body>
      <div class="right"><img src="static/basex.svg" width="96"/></div>
      <h2>BaseX HTTP Services</h2>
			<div>Welcome to the BaseX HTTP Services, which allow you to...</div>
			<ul>
				<li>Query and modify databases via <a href="http://docs.basex.org/wiki/REST">REST</a> (try <a href='rest'>here</a>)</li>
				<li>Browse and update resources via <a href="http://docs.basex.org/wiki/WebDAV">WebDAV</a></li>
				<li>Create web applications and services with <a href="http://docs.basex.org/wiki/RESTXQ">RESTXQ</a></li>
			</ul>

      <p>This page was generated by RESTXQ. It facilitates the
      use of XQuery as a server-side processing language for the Web.</p>

      <h3>Example 1</h3>
      <p>The following links return different results.
      Both are generated by the same RESTXQ function:</p>
      <ul>
        <li><a href="hello/World">/hello/World</a></li>
        <li><a href="hello/Universe">/hello/Universe</a></li>
      </ul>

      <h3>Example 2</h3>
      <p>The next example presents how form data is processed via RESTXQ and the POST method:</p>
      <form method="post" action="form">
        <p>Your message:<br />
        <input name="message" size="50"></input>
        <input type="submit" /></p>
      </form>

      <h3>Example 3</h3>
      <p>The source code of the file that created this page
      (<code>{ static-base-uri() }</code>) is shown below:</p>
      <pre>{ unparsed-text(static-base-uri()) }</pre>
    </body>
  </html>
};

(:~
 : This function returns an XML response message.
 : @param $world  string to be included in the response
 : @return response element 
 :)
declare
  %rest:path("/hello/{$world}")
  %rest:GET
  function page:hello(
    $world as xs:string)
    as element(response)
{
  <response>
    <title>Hello { $world }!</title>
    <time>The current time is: { current-time() }</time>
  </response>
};


(:~
 : This function returns the result of a form request.
 : @param  $message  message to be included in the response
 : @param $agent  user agent string
 : @return response element 
 :)
declare
  %rest:path("/form")
  %rest:POST
  %rest:form-param("message","{$message}", "nothing")
  %rest:header-param("User-Agent", "{$agent}")
  function page:hello-postman(
    $message as xs:string,
    $agent   as xs:string*)
    as element(response)
{
  <response type='form'>
    <message>{ $message }</message>
    <user-agent>{ $agent }</user-agent>
  </response>
};


(:Myself made code==============  form   ===========================================:)


 (:function book2:)
 declare
  %rest:path("/book2/source")
  %rest:GET
  function page:book2(){
    let $contents  := doc("book2.xml")
    return $contents
  };

 (:function bookxsl:)
 declare
  %rest:path("/book2/xsl")
  %rest:GET
  function page:book_xsl(){
    let $contents  := doc("book.xsl")
    return $contents
  };

 (:function modify:)
 declare
  %rest:path("/book2/form2/modify/{$num}")
  %rest:POST
  %rest:form-param("mod","{$mod}", "(no message)")
  %updating
  function page:modify($mod as xs:string,$num as xs:int){
    replace value of node doc("book2.xml")/book/body/item[$num]/contents with $mod
  };


 (:function book2:)
declare
  %rest:path("/book2/{$num}")
  %rest:GET

  %output:method("xhtml")
  %output:omit-xml-declaration("no")
  %output:doctype-public("-//W3C//DTD XHTML 1.0 Transitional//EN")
  %output:doctype-system("http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd")
  function page:book2($num as xs:int)
    {
       let $title  := doc("book2.xml")/book/body/item[$num]/title/text()
       let $contents  := doc("book2.xml")/book/body/item[$num]/contents/text()

  return
  <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <title>Book2 Editor</title>
      <link rel="stylesheet" type="text/css" href="../static/style.css"/>

    </head>
    <body>
    <div class = "container">
    <div id="header"> <h1>{$title}</h1></div>
    
    <div class="sidebar" id="left_side"></div>
    <div class="sidebar" id="right_side">
      <div class="btn"><a href="source" target="_blank">book2</a></div><br/>
      <div class="btn"><a href="xsl" target="_blank">book_xsl</a></div><br/>
      <div class="btn"><a href="http://localhost:8080/fop/fop?xml=/Program Files (x86)/BaseX/webapp/book2.xml&amp;xslt=/Program Files (x86)/BaseX/webapp/book.xsl" target="_blank">fop</a></div>
      <br/>
    </div>
    <div id="content">
    <button ><a href="1">1</a></button>  
    <button ><a href="2">2</a></button>  
    <button ><a href="3">3</a></button>  
    <button ><a href="4">4</a></button>  
    <button ><a href="5">5</a></button>  
    <button ><a href="6">6</a></button>  
    <button ><a href="7">7</a></button>  
    <button ><a href="8">8</a></button>  
    <button ><a href="9">9</a></button>  
    <button ><a href="10">10</a></button>  
    <button ><a href="11">11</a></button>  
    <button ><a href="12">12</a></button>  
    <button ><a href="13">13</a></button>  
    <button ><a href="14">14</a></button>  
    <button ><a href="15">15</a></button>  
    <button ><a href="16">16</a></button>  
    <button ><a href="17">17</a></button>  
    <button ><a href="18">18</a></button>  
    <button ><a href="19">19</a></button>  
    <button ><a href="20">20</a></button>  
     
      <form method="post" action="form2/modify/{$num}">
       <input type="submit" value = "modify" />
        <textarea name="mod" rows="40" cols="90">{$contents}</textarea>
       
      </form><br/>
      </div>
      <div id="bottom"></div>
    </div>
    </body>
  </html>
    };



(:~
 : This function returns the result of a form request.
 
 :)
 (:function sentences:)
declare
  %rest:path("/bookedit/sentences")
  %rest:POST
  %rest:form-param("num","{$num}", "(no message)")
  %rest:form-param("tag","{$tag}", "(no message)")
  %output:method("xhtml")
  %output:omit-xml-declaration("no")
  %output:doctype-public("-//W3C//DTD XHTML 1.0 Transitional//EN")
  %output:doctype-system("http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd")
  function page:sentences($num as xs:int, $tag as xs:string)
    {
        for $data in doc("sentences.xml")/sentences/sentence[tags/tag=$tag]
        order by  xs:integer($data/tags/length)
        return 
        <p>{$data/text()}</p>
    };
 
 
 (:function title:)
 declare
  %rest:path("/bookedit/form2/title/{$num}")
  %rest:POST
  %rest:form-param("title","{$title}", "(no message)")
  %updating
  function page:title($title as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/title with $title
  };  

 
 (:function before_start:)
 declare
  %rest:path("/bookedit/form2/before_start/{$num}")
  %rest:POST
  %rest:form-param("before_start","{$before_start}", "(no message)")
  %updating
  function page:before_start($before_start as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/before_start with $before_start
  };  

 (:function basic_concept:)
 declare
  %rest:path("/bookedit/form2/basic_concept/{$num}")
  %rest:POST
  %rest:form-param("basic_concept","{$basic_concept}", "nothing")
  %updating
  function page:basic_concept($basic_concept as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/basic_concept/concept with $basic_concept
  };    
  
 (:function mean:) 
 declare
  %rest:path("/bookedit/form2/mean/{$num}")
  %rest:POST
  %rest:form-param("mean","{$mean}", "(no message)")
  %updating
  function page:mean($mean as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/basic_concept/mean with $mean
  };    
 
 
 (:function form:)
 declare
  %rest:path("/bookedit/form2/form/{$num}")
  %rest:POST
  %rest:form-param("structure","{$structure}", "(no message)")
  %updating
  function page:structure($structure as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/basic_concept/form with $structure
  };  
 
 (:function ex:)
 declare
  %rest:path("/bookedit/form2/ex/{$num}")
  %rest:POST
  %rest:form-param("ex","{$ex}", "(no message)")
  %updating
  function page:ex($ex as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/basic_concept/ex with $ex
  };  
 
 (:function in_korean:)
 declare
  %rest:path("/bookedit/form2/in_korean/{$num}")
  %rest:POST
  %rest:form-param("in_korean","{$in_korean}", "(no message)")
  %updating
  function page:in_korean($in_korean as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/basic_concept/in_Korean with $in_korean
  };  
 
 (:function in_sentence:)
 declare
  %rest:path("/bookedit/form2/in_sentence/{$num}")
  %rest:POST
  %rest:form-param("in_sentence","{$in_sentence}", "(no message)")
  %updating
  function page:in_sentence($in_sentence as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/basic_concept/in_sentence/how_to with $in_sentence
  };  
 
 (:function ex_s1:)
 declare
  %rest:path("/bookedit/form2/ex_s1/{$num}")
  %rest:POST
  %rest:form-param("ex_s1","{$ex_s1}", "(no message)")
  %updating
  function page:ex_s1($ex_s1 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/basic_concept/in_sentence/ex_s[1] with $ex_s1
  };  
 
 
 
 (:function ex_s2:)
 declare
  %rest:path("/bookedit/form2/ex_s2/{$num}")
  %rest:POST
  %rest:form-param("ex_s2","{$ex_s2}", "(no message)")
  %updating
  function page:ex_s2($ex_s2 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/basic_concept/in_sentence/ex_s[2] with $ex_s2
  };  
 
 (:function ex_s3:)
 declare
  %rest:path("/bookedit/form2/ex_s3/{$num}")
  %rest:POST
  %rest:form-param("ex_s3","{$ex_s3}", "(no message)")
  %updating
  function page:ex_s3($ex_s3 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/basic_concept/in_sentence/ex_s[3] with $ex_s3
  };  
 
 (:function ex_s4:)
 declare
  %rest:path("/bookedit/form2/ex_s4/{$num}")
  %rest:POST
  %rest:form-param("ex_s4","{$ex_s4}", "(no message)")
  %updating
  function page:ex_s4($ex_s4 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/basic_concept/in_sentence/ex_s[4] with $ex_s4
  };  
 
 (:function reason_longer:)
 declare
  %rest:path("/bookedit/form2/reason_longer/{$num}")
  %rest:POST
  %rest:form-param("reason_longer","{$reason_longer}", "(no message)")
  %updating
  function page:reason_longer($reason_longer as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/basic_concept/reason_getting_longer with $reason_longer
  };  
 
 (:function explanation:)
 declare
  %rest:path("/bookedit/form2/explanation/{$num}")
  %rest:POST
  %rest:form-param("explanation","{$explanation}", "(no message)")
  %updating
  function page:explanation($explanation as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/explanation with $explanation
  };  
 
 (:function level1_1:)
 declare
  %rest:path("/bookedit/form2/level1_1/{$num}")
  %rest:POST
  %rest:form-param("level1_1","{$level1_1}", "(no message)")
  %updating
  function page:level1_1($level1_1 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[1] with $level1_1
  };  
 
 
 (:function level1_2:)
 declare
  %rest:path("/bookedit/form2/level1_2/{$num}")
  %rest:POST
  %rest:form-param("level1_2","{$level1_2}", "(no message)")
  %updating
  function page:level1_2($level1_2 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[2] with $level1_2
  };  
 
 (:function level1_3:)
 declare
  %rest:path("/bookedit/form2/level1_3/{$num}")
  %rest:POST
  %rest:form-param("level1_3","{$level1_3}", "(no message)")
  %updating
  function page:level1_3($level1_3 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[3] with $level1_3
  };  
 
 (:function level1_4:)
 declare
  %rest:path("/bookedit/form2/level1_4/{$num}")
  %rest:POST
  %rest:form-param("level1_4","{$level1_4}", "(no message)")
  %updating
  function page:level1_4($level1_4 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[4] with $level1_4
  };  
 
 (:function level1_5:)
 declare
  %rest:path("/bookedit/form2/level1_5/{$num}")
  %rest:POST
  %rest:form-param("level1_5","{$level1_5}", "(no message)")
  %updating
  function page:level1_5($level1_5 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[5] with $level1_5
  };  
 
 (:function level1_6:)
 declare
  %rest:path("/bookedit/form2/level1_6/{$num}")
  %rest:POST
  %rest:form-param("level1_6","{$level1_6}", "(no message)")
  %updating
  function page:level1_6($level1_6 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[6] with $level1_6
  };  
 
 (:function level1_7:)
 declare
  %rest:path("/bookedit/form2/level1_7/{$num}")
  %rest:POST
  %rest:form-param("level1_7","{$level1_7}", "(no message)")
  %updating
  function page:level1_7($level1_7 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[7] with $level1_7
  };  
 
 (:function level1_8:)
 declare
  %rest:path("/bookedit/form2/level1_8/{$num}")
  %rest:POST
  %rest:form-param("level1_8","{$level1_8}", "(no message)")
  %updating
  function page:level1_8($level1_8 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[8] with $level1_8
  };  
 
 (:function level1_9:)
 declare
  %rest:path("/bookedit/form2/level1_9/{$num}")
  %rest:POST
  %rest:form-param("level1_9","{$level1_9}", "(no message)")
  %updating
  function page:level1_9($level1_9 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[9] with $level1_9
  };  
 
 (:function level2_1:)
 declare
  %rest:path("/bookedit/form2/level2_1/{$num}")
  %rest:POST
  %rest:form-param("level2_1","{$level2_1}", "(no message)")
  %updating
  function page:level2_1($level2_1 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[1] with $level2_1
  };  
 
 (:function level2_2:)
 declare
  %rest:path("/bookedit/form2/level2_2/{$num}")
  %rest:POST
  %rest:form-param("level2_2","{$level2_2}", "(no message)")
  %updating
  function page:level2_2($level2_2 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[2] with $level2_2
  };  
 
 (:function level2_3:)
 declare
  %rest:path("/bookedit/form2/level2_3/{$num}")
  %rest:POST
  %rest:form-param("level2_3","{$level2_3}", "(no message)")
  %updating
  function page:level2_3($level2_3 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[3] with $level2_3
  };  
 
 (:function level2_4:)
 declare
  %rest:path("/bookedit/form2/level2_4/{$num}")
  %rest:POST
  %rest:form-param("level2_4","{$level2_4}", "(no message)")
  %updating
  function page:level2_4($level2_4 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[4] with $level2_4
  };  
 
 (:function level2_5:)
 declare
  %rest:path("/bookedit/form2/level2_5/{$num}")
  %rest:POST
  %rest:form-param("level2_5","{$level2_5}", "(no message)")
  %updating
  function page:level2_5($level2_5 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[5] with $level2_5
  };  
 
 (:function level2_6:)
 declare
  %rest:path("/bookedit/form2/level2_6/{$num}")
  %rest:POST
  %rest:form-param("level2_6","{$level2_6}", "(no message)")
  %updating
  function page:level2_6($level2_6 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[6] with $level2_6
  };  
 
 (:function level2_7:)
 declare
  %rest:path("/bookedit/form2/level2_7/{$num}")
  %rest:POST
  %rest:form-param("level2_7","{$level2_7}", "(no message)")
  %updating
  function page:level2_7($level2_7 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[7] with $level2_7
  };  
 
 (:function level2_8:)
 declare
  %rest:path("/bookedit/form2/level2_8/{$num}")
  %rest:POST
  %rest:form-param("level2_8","{$level2_8}", "(no message)")
  %updating
  function page:level2_8($level2_8 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[8] with $level2_8
  };  
 
 (:function level2_9:)
 declare
  %rest:path("/bookedit/form2/level2_9/{$num}")
  %rest:POST
  %rest:form-param("level2_9","{$level2_9}", "(no message)")
  %updating
  function page:level2_9($level2_9 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[9] with $level2_9
  };  
 
 (:function level3_1:)
 declare
  %rest:path("/bookedit/form2/level3_1/{$num}")
  %rest:POST
  %rest:form-param("level3_1","{$level3_1}", "(no message)")
  %updating
  function page:level3_1($level3_1 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[1] with $level3_1
  };  
 
 (:function level3_2:)
 declare
  %rest:path("/bookedit/form2/level3_2/{$num}")
  %rest:POST
  %rest:form-param("level3_2","{$level3_2}", "(no message)")
  %updating
  function page:level3_2($level3_2 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[2] with $level3_2
  };  
 
 (:function level3_3:)
 declare
  %rest:path("/bookedit/form2/level3_3/{$num}")
  %rest:POST
  %rest:form-param("level3_3","{$level3_3}", "(no message)")
  %updating
  function page:level3_3($level3_3 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[3] with $level3_3
  };  
 
 (:function level3_4:)
 declare
  %rest:path("/bookedit/form2/level3_4/{$num}")
  %rest:POST
  %rest:form-param("level3_4","{$level3_4}", "(no message)")
  %updating
  function page:level3_4($level3_4 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[4] with $level3_4
  };  
 
 (:function level3_5:)
 declare
  %rest:path("/bookedit/form2/level3_5/{$num}")
  %rest:POST
  %rest:form-param("level3_5","{$level3_5}", "(no message)")
  %updating
  function page:level3_5($level3_5 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[5] with $level3_5
  };  
 
 (:function level3_6:)
 declare
  %rest:path("/bookedit/form2/level3_6/{$num}")
  %rest:POST
  %rest:form-param("level3_6","{$level3_6}", "(no message)")
  %updating
  function page:level3_6($level3_6 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[6] with $level3_6
  };  
 
 (:function level3_7:)
 declare
  %rest:path("/bookedit/form2/level3_7/{$num}")
  %rest:POST
  %rest:form-param("level3_7","{$level3_7}", "(no message)")
  %updating
  function page:level3_7($level3_7 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[7] with $level3_7
  };  
 
 (:function level3_8:)
 declare
  %rest:path("/bookedit/form2/level3_8/{$num}")
  %rest:POST
  %rest:form-param("level3_8","{$level3_8}", "(no message)")
  %updating
  function page:level3_8($level3_8 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[8] with $level3_8
  };  
 
 (:function level3_9:)
 declare
  %rest:path("/bookedit/form2/level3_9/{$num}")
  %rest:POST
  %rest:form-param("level3_9","{$level3_9}", "(no message)")
  %updating
  function page:level3_9($level3_9 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[9] with $level3_9
  };  
 
 (:function t_level1_1:)
 declare
  %rest:path("/bookedit/form2/t_level1_1/{$num}")
  %rest:POST
  %rest:form-param("t_level1_1","{$t_level1_1}", "(no message)")
  %updating
  function page:t_level1_1($t_level1_1 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[1] with $t_level1_1
  };  
 
 (:function t_level1_2:)
 declare
  %rest:path("/bookedit/form2/t_level1_2/{$num}")
  %rest:POST
  %rest:form-param("t_level1_2","{$t_level1_2}", "(no message)")
  %updating
  function page:t_level1_2($t_level1_2 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[2] with $t_level1_2
  };  
 
 (:function t_level1_3:)
 declare
  %rest:path("/bookedit/form2/t_level1_3/{$num}")
  %rest:POST
  %rest:form-param("t_level1_3","{$t_level1_3}", "(no message)")
  %updating
  function page:t_level1_3($t_level1_3 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[3] with $t_level1_3
  };  
 
 (:function t_level1_4:)
 declare
  %rest:path("/bookedit/form2/t_level1_4/{$num}")
  %rest:POST
  %rest:form-param("t_level1_4","{$t_level1_4}", "(no message)")
  %updating
  function page:t_level1_4($t_level1_4 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[4] with $t_level1_4
  };  
 
 (:function t_level1_5:)
 declare
  %rest:path("/bookedit/form2/t_level1_5/{$num}")
  %rest:POST
  %rest:form-param("t_level1_5","{$t_level1_5}", "(no message)")
  %updating
  function page:t_level1_5($t_level1_5 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[5] with $t_level1_5
  };  
 
 (:function t_level1_6:)
 declare
  %rest:path("/bookedit/form2/t_level1_6/{$num}")
  %rest:POST
  %rest:form-param("t_level1_6","{$t_level1_6}", "(no message)")
  %updating
  function page:t_level1_6($t_level1_6 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[6] with $t_level1_6
  };  
 
 (:function t_level1_7:)
 declare
  %rest:path("/bookedit/form2/t_level1_7/{$num}")
  %rest:POST
  %rest:form-param("t_level1_7","{$t_level1_7}", "(no message)")
  %updating
  function page:t_level1_7($t_level1_7 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[7] with $t_level1_7
  };  
 
 (:function t_level1_8:)
 declare
  %rest:path("/bookedit/form2/t_level1_8/{$num}")
  %rest:POST
  %rest:form-param("t_level1_8","{$t_level1_8}", "(no message)")
  %updating
  function page:t_level1_8($t_level1_8 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[8] with $t_level1_8
  };  
 
 (:function t_level1_9:)
 declare
  %rest:path("/bookedit/form2/t_level1_9/{$num}")
  %rest:POST
  %rest:form-param("t_level1_9","{$t_level1_9}", "(no message)")
  %updating
  function page:t_level1_9($t_level1_9 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[9] with $t_level1_9
  };  
 
 (:function t_level2_1:)
 declare
  %rest:path("/bookedit/form2/t_level2_1/{$num}")
  %rest:POST
  %rest:form-param("t_level2_1","{$t_level2_1}", "(no message)")
  %updating
  function page:t_level2_1($t_level2_1 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[1] with $t_level2_1
  };  
 
 (:function t_level2_2:)
 declare
  %rest:path("/bookedit/form2/t_level2_2/{$num}")
  %rest:POST
  %rest:form-param("t_level2_2","{$t_level2_2}", "(no message)")
  %updating
  function page:t_level2_2($t_level2_2 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[2] with $t_level2_2
  };  
 
 (:function t_level2_3:)
 declare
  %rest:path("/bookedit/form2/t_level2_3/{$num}")
  %rest:POST
  %rest:form-param("t_level2_3","{$t_level2_3}", "(no message)")
  %updating
  function page:t_level2_3($t_level2_3 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[3] with $t_level2_3
  };  
 
 (:function t_level2_4:)
 declare
  %rest:path("/bookedit/form2/t_level2_4/{$num}")
  %rest:POST
  %rest:form-param("t_level2_4","{$t_level2_4}", "(no message)")
  %updating
  function page:t_level2_4($t_level2_4 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[4] with $t_level2_4
  };  
 
 (:function t_level2_5:)
 declare
  %rest:path("/bookedit/form2/t_level2_5/{$num}")
  %rest:POST
  %rest:form-param("t_level2_5","{$t_level2_5}", "(no message)")
  %updating
  function page:t_level2_5($t_level2_5 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[5] with $t_level2_5
  };  
 
 (:function t_level2_6:)
 declare
  %rest:path("/bookedit/form2/t_level2_6/{$num}")
  %rest:POST
  %rest:form-param("t_level2_6","{$t_level2_6}", "(no message)")
  %updating
  function page:t_level2_6($t_level2_6 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[6] with $t_level2_6
  };  
 
 (:function t_level2_7:)
 declare
  %rest:path("/bookedit/form2/t_level2_7/{$num}")
  %rest:POST
  %rest:form-param("t_level2_7","{$t_level2_7}", "(no message)")
  %updating
  function page:t_level2_7($t_level2_7 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[7] with $t_level2_7
  };  
 
 (:function t_level2_8:)
 declare
  %rest:path("/bookedit/form2/t_level2_8/{$num}")
  %rest:POST
  %rest:form-param("t_level2_8","{$t_level2_8}", "(no message)")
  %updating
  function page:t_level2_8($t_level2_8 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[8] with $t_level2_8
  };  
 
 (:function t_level2_9:)
 declare
  %rest:path("/bookedit/form2/t_level2_9/{$num}")
  %rest:POST
  %rest:form-param("t_level2_9","{$t_level2_9}", "(no message)")
  %updating
  function page:t_level2_9($t_level2_9 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[9] with $t_level2_9
  };  
 
 (:function t_level3_1:)
 declare
  %rest:path("/bookedit/form2/t_level3_1/{$num}")
  %rest:POST
  %rest:form-param("t_level3_1","{$t_level3_1}", "(no message)")
  %updating
  function page:t_level3_1($t_level3_1 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[1] with $t_level3_1
  };  
 
 (:function t_level3_2:)
 declare
  %rest:path("/bookedit/form2/t_level3_2/{$num}")
  %rest:POST
  %rest:form-param("t_level3_2","{$t_level3_2}", "(no message)")
  %updating
  function page:t_level3_2($t_level3_2 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[2] with $t_level3_2
  };  
 
 (:function t_level3_3:)
 declare
  %rest:path("/bookedit/form2/t_level3_3/{$num}")
  %rest:POST
  %rest:form-param("t_level3_3","{$t_level3_3}", "(no message)")
  %updating
  function page:t_level3_3($t_level3_3 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[3] with $t_level3_3
  };  
 
 (:function t_level3_4:)
 declare
  %rest:path("/bookedit/form2/t_level3_4/{$num}")
  %rest:POST
  %rest:form-param("t_level3_4","{$t_level3_4}", "(no message)")
  %updating
  function page:t_level3_4($t_level3_4 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[4] with $t_level3_4
  };  
 
 (:function t_level3_5:)
 declare
  %rest:path("/bookedit/form2/t_level3_5/{$num}")
  %rest:POST
  %rest:form-param("t_level3_5","{$t_level3_5}", "(no message)")
  %updating
  function page:t_level3_5($t_level3_5 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[5] with $t_level3_5
  };  
 
 (:function t_level3_6:)
 declare
  %rest:path("/bookedit/form2/t_level3_6/{$num}")
  %rest:POST
  %rest:form-param("t_level3_6","{$t_level3_6}", "(no message)")
  %updating
  function page:t_level3_6($t_level3_6 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[6] with $t_level3_6
  };  
 
 (:function t_level3_7:)
 declare
  %rest:path("/bookedit/form2/t_level3_7/{$num}")
  %rest:POST
  %rest:form-param("t_level3_7","{$t_level3_7}", "(no message)")
  %updating
  function page:t_level3_7($t_level3_7 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[7] with $t_level3_7
  };  
 
 (:function t_level3_8:)
 declare
  %rest:path("/bookedit/form2/t_level3_8/{$num}")
  %rest:POST
  %rest:form-param("t_level3_8","{$t_level3_8}", "(no message)")
  %updating
  function page:t_level3_8($t_level3_8 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[8] with $t_level3_8
  };  
 
 (:function t_level3_9:)
 declare
  %rest:path("/bookedit/form2/t_level3_9/{$num}")
  %rest:POST
  %rest:form-param("t_level3_9","{$t_level3_9}", "(no message)")
  %updating
  function page:t_level3_9($t_level3_9 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[9] with $t_level3_9
  };  
 
 (:function p_1:)
 declare
  %rest:path("/bookedit/form2/p_1/{$num}")
  %rest:POST
  %rest:form-param("p_1","{$p_1}", "(no message)")
  %updating
  function page:p_1($p_1 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/practice/p[1] with $p_1
  };  
 
 (:function p_2:)
 declare
  %rest:path("/bookedit/form2/p_2/{$num}")
  %rest:POST
  %rest:form-param("p_2","{$p_2}", "(no message)")
  %updating
  function page:p_2($p_2 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/practice/p[2] with $p_2
  };  
 
 (:function p_3:)
 declare
  %rest:path("/bookedit/form2/p_3/{$num}")
  %rest:POST
  %rest:form-param("p_3","{$p_3}", "(no message)")
  %updating
  function page:p_3($p_3 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/practice/p[3] with $p_3
  };  
 
 (:function p_4:)
 declare
  %rest:path("/bookedit/form2/p_4/{$num}")
  %rest:POST
  %rest:form-param("p_4","{$p_4}", "(no message)")
  %updating
  function page:p_4($p_4 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/practice/p[4] with $p_4
  };  
 
 (:function p_5:)
 declare
  %rest:path("/bookedit/form2/p_5/{$num}")
  %rest:POST
  %rest:form-param("p_5","{$p_5}", "(no message)")
  %updating
  function page:p_5($p_5 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/practice/p[5] with $p_5
  };  
 
 (:function p_6:)
 declare
  %rest:path("/bookedit/form2/p_6/{$num}")
  %rest:POST
  %rest:form-param("p_6","{$p_6}", "(no message)")
  %updating
  function page:p_6($p_6 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/practice/p[6] with $p_6
  };  
 
 (:function p_7:)
 declare
  %rest:path("/bookedit/form2/p_7/{$num}")
  %rest:POST
  %rest:form-param("p_7","{$p_7}", "(no message)")
  %updating
  function page:p_7($p_7 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/practice/p[7] with $p_7
  };  
 
 (:function p_8:)
 declare
  %rest:path("/bookedit/form2/p_8/{$num}")
  %rest:POST
  %rest:form-param("p_8","{$p_8}", "(no message)")
  %updating
  function page:p_8($p_8 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/practice/p[8] with $p_8
  };  
 
 (:function p_9:)
 declare
  %rest:path("/bookedit/form2/p_9/{$num}")
  %rest:POST
  %rest:form-param("p_9","{$p_9}", "(no message)")
  %updating
  function page:p_9($p_9 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/practice/p[9] with $p_9
  };  
 
 (:function p_a_1:)
 declare
  %rest:path("/bookedit/form2/p_a_1/{$num}")
  %rest:POST
  %rest:form-param("p_a_1","{$p_a_1}", "(no message)")
  %updating
  function page:p_a_1($p_a_1 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/answers/p[1] with $p_a_1
  };  
 
 (:function p_a_2:)
 declare
  %rest:path("/bookedit/form2/p_a_2/{$num}")
  %rest:POST
  %rest:form-param("p_a_2","{$p_a_2}", "(no message)")
  %updating
  function page:p_a_2($p_a_2 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/answers/p[2] with $p_a_2
  };  
 
 (:function p_a_3:)
 declare
  %rest:path("/bookedit/form2/p_a_3/{$num}")
  %rest:POST
  %rest:form-param("p_a_3","{$p_a_3}", "(no message)")
  %updating
  function page:p_a_3($p_a_3 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/answers/p[3] with $p_a_3
  };  
 
 (:function p_a_4:)
 declare
  %rest:path("/bookedit/form2/p_a_4/{$num}")
  %rest:POST
  %rest:form-param("p_a_4","{$p_a_4}", "(no message)")
  %updating
  function page:p_a_4($p_a_4 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/answers/p[4] with $p_a_4
  };  
 
 (:function p_a_5:)
 declare
  %rest:path("/bookedit/form2/p_a_5/{$num}")
  %rest:POST
  %rest:form-param("p_a_5","{$p_a_5}", "(no message)")
  %updating
  function page:p_a_5($p_a_5 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/answers/p[5] with $p_a_5
  };  
 
 (:function p_a_6:)
 declare
  %rest:path("/bookedit/form2/p_a_6/{$num}")
  %rest:POST
  %rest:form-param("p_a_6","{$p_a_6}", "(no message)")
  %updating
  function page:p_a_6($p_a_6 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/answers/p[6] with $p_a_6
  };  
 
 (:function p_a_7:)
 declare
  %rest:path("/bookedit/form2/p_a_7/{$num}")
  %rest:POST
  %rest:form-param("p_a_7","{$p_a_7}", "(no message)")
  %updating
  function page:p_a_7($p_a_7 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/answers/p[7] with $p_a_7
  };  
 
 (:function p_a_8:)
 declare
  %rest:path("/bookedit/form2/p_a_8/{$num}")
  %rest:POST
  %rest:form-param("p_a_8","{$p_a_8}", "(no message)")
  %updating
  function page:p_a_8($p_a_8 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/answers/p[8] with $p_a_8
  };  
 
 (:function p_a_9:)
 declare
  %rest:path("/bookedit/form2/p_a_9/{$num}")
  %rest:POST
  %rest:form-param("p_a_9","{$p_a_9}", "(no message)")
  %updating
  function page:p_a_9($p_a_9 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/answers/p[9] with $p_a_9
  };  
 
 (:function l_s_1:)
 declare
  %rest:path("/bookedit/form2/l_s_1/{$num}")
  %rest:POST
  %rest:form-param("l_s_1","{$l_s_1}", "(no message)")
  %updating
  function page:l_s_1($l_s_1 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[1] with $l_s_1
  };  
 
 (:function l_s_2:)
 declare
  %rest:path("/bookedit/form2/l_s_2/{$num}")
  %rest:POST
  %rest:form-param("l_s_2","{$l_s_2}", "(no message)")
  %updating
  function page:l_s_2($l_s_2 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[2] with $l_s_2
  };  
 
 (:function l_s_3:)
 declare
  %rest:path("/bookedit/form2/l_s_3/{$num}")
  %rest:POST
  %rest:form-param("l_s_3","{$l_s_3}", "(no message)")
  %updating
  function page:l_s_3($l_s_3 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[3] with $l_s_3
  };  
 
 (:function l_s_4:)
 declare
  %rest:path("/bookedit/form2/l_s_4/{$num}")
  %rest:POST
  %rest:form-param("l_s_4","{$l_s_4}", "(no message)")
  %updating
  function page:l_s_4($l_s_4 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[4] with $l_s_4
  };  
 
 (:function l_s_5:)
 declare
  %rest:path("/bookedit/form2/l_s_5/{$num}")
  %rest:POST
  %rest:form-param("l_s_5","{$l_s_5}", "(no message)")
  %updating
  function page:l_s_5($l_s_5 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[5] with $l_s_5
  };  
 
 (:function l_s_6:)
 declare
  %rest:path("/bookedit/form2/l_s_6/{$num}")
  %rest:POST
  %rest:form-param("l_s_6","{$l_s_6}", "(no message)")
  %updating
  function page:l_s_6($l_s_6 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[6] with $l_s_6
  };  
 
 (:function l_s_7:)
 declare
  %rest:path("/bookedit/form2/l_s_7/{$num}")
  %rest:POST
  %rest:form-param("l_s_7","{$l_s_7}", "(no message)")
  %updating
  function page:l_s_7($l_s_7 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[7] with $l_s_7
  };  
 
 (:function l_s_8:)
 declare
  %rest:path("/bookedit/form2/l_s_8/{$num}")
  %rest:POST
  %rest:form-param("l_s_8","{$l_s_8}", "(no message)")
  %updating
  function page:l_s_8($l_s_8 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[8] with $l_s_8
  };  
 
 (:function l_s_9:)
 declare
  %rest:path("/bookedit/form2/l_s_9/{$num}")
  %rest:POST
  %rest:form-param("l_s_9","{$l_s_9}", "(no message)")
  %updating
  function page:l_s_9($l_s_9 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[9] with $l_s_9
  };  
 
 (:function t_l_s_1:)
 declare
  %rest:path("/bookedit/form2/t_l_s_1/{$num}")
  %rest:POST
  %rest:form-param("t_l_s_1","{$t_l_s_1}", "(no message)")
  %updating
  function page:t_l_s_1($t_l_s_1 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[1] with $t_l_s_1
  };  
 
 (:function t_l_s_2:)
 declare
  %rest:path("/bookedit/form2/t_l_s_2/{$num}")
  %rest:POST
  %rest:form-param("t_l_s_2","{$t_l_s_2}", "(no message)")
  %updating
  function page:t_l_s_2($t_l_s_2 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[2] with $t_l_s_2
  };  
 
 (:function t_l_s_3:)
 declare
  %rest:path("/bookedit/form2/t_l_s_3/{$num}")
  %rest:POST
  %rest:form-param("t_l_s_3","{$t_l_s_3}", "(no message)")
  %updating
  function page:t_l_s_3($t_l_s_3 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[3] with $t_l_s_3
  };  
 
 (:function t_l_s_4:)
 declare
  %rest:path("/bookedit/form2/t_l_s_4/{$num}")
  %rest:POST
  %rest:form-param("t_l_s_4","{$t_l_s_4}", "(no message)")
  %updating
  function page:t_l_s_4($t_l_s_4 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[4] with $t_l_s_4
  };  
 
 (:function t_l_s_5:)
 declare
  %rest:path("/bookedit/form2/t_l_s_5/{$num}")
  %rest:POST
  %rest:form-param("t_l_s_5","{$t_l_s_5}", "(no message)")
  %updating
  function page:t_l_s_5($t_l_s_5 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[5] with $t_l_s_5
  };  
 
 (:function t_l_s_6:)
 declare
  %rest:path("/bookedit/form2/t_l_s_6/{$num}")
  %rest:POST
  %rest:form-param("t_l_s_6","{$t_l_s_6}", "(no message)")
  %updating
  function page:t_l_s_6($t_l_s_6 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[6] with $t_l_s_6
  };  
 
 (:function t_l_s_7:)
 declare
  %rest:path("/bookedit/form2/t_l_s_7/{$num}")
  %rest:POST
  %rest:form-param("t_l_s_7","{$t_l_s_7}", "(no message)")
  %updating
  function page:t_l_s_7($t_l_s_7 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[7] with $t_l_s_7
  };  
 
  (:function t_l_s_8:)
 declare
  %rest:path("/bookedit/form2/t_l_s_8/{$num}")
  %rest:POST
  %rest:form-param("t_l_s_8","{$t_l_s_8}", "(no message)")
  %updating
  function page:t_l_s_8($t_l_s_8 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[8] with $t_l_s_8
  };  
  
 (:function t_l_s_9:)
 declare
  %rest:path("/bookedit/form2/t_l_s_9/{$num}")
  %rest:POST
  %rest:form-param("t_l_s_9","{$t_l_s_9}", "(no message)")
  %updating
  function page:t_l_s_9($t_l_s_9 as xs:string,$num as xs:int){
    replace value of node doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[9] with $t_l_s_9
    
  };  
 
 
 
 (:function insert:)
 declare
  %rest:path("/bookedit/update/insert")
  %rest:GET
  %updating
  function page:insert(){
    insert node <before_start>sample</before_start> after doc("book.xml")/book/body/item[1]/title
  };   

 (:function next:)
 declare
  %rest:path("/bookedit/next")
  %rest:GET
  function page:next(){
  let $title  := doc("book.xml")/book/body/item[3]/title/text()
  return
  http:send-request(<http:request method='get' href='http://localhost:8984/bookedit/12'/>)
  
  };   


(:~
 : This function returns an XML response message.
 : @param $world  string to be included in the response
 : @return response element 
 :)
declare
  %rest:path("/bookedit/{$num}")
  %rest:GET
  function page:bookeditinterface($num as xs:int)
{
  let $title  := doc("book.xml")/book/body/item[$num]/title/text()
  let $before_start  := doc("book.xml")/book/body/item[$num]/before_start/text()  
  let $basic_concept := doc("book.xml")/book/body/item[$num]/contents/basic_concept/concept/text()
  let $contents := doc("book.xml")/book/body/item[$num]/title/text()
  let $mean := doc("book.xml")/book/body/item[$num]/contents/basic_concept/mean/text()
  let $structure := doc("book.xml")/book/body/item[$num]/contents/basic_concept/form/text()
  let $ex := doc("book.xml")/book/body/item[$num]/contents/basic_concept/ex/text()
  let $in_korean := doc("book.xml")/book/body/item[$num]/contents/basic_concept/in_Korean/text()
  let $in_sentence := doc("book.xml")/book/body/item[$num]/contents/basic_concept/in_sentence/how_to/text()
  let $ex_s1 :=  doc("book.xml")/book/body/item[$num]/contents/basic_concept/in_sentence/ex_s[1]/text()
  let $ex_s2 :=  doc("book.xml")/book/body/item[$num]/contents/basic_concept/in_sentence/ex_s[2]/text()
  let $ex_s3 :=  doc("book.xml")/book/body/item[$num]/contents/basic_concept/in_sentence/ex_s[3]/text()
  let $ex_s4 :=  doc("book.xml")/book/body/item[$num]/contents/basic_concept/in_sentence/ex_s[4]/text()
  let $reason_longer :=  doc("book.xml")/book/body/item[$num]/contents/basic_concept/reason_getting_longer/text()
  let $explanation :=  doc("book.xml")/book/body/item[$num]/contents/explanation/text()
 
  
  let $level1_1 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[1]/text()
  let $level1_2 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[2]/text()
  let $level1_3 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[3]/text()
  let $level1_4 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[4]/text()
  let $level1_5 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[5]/text()
  let $level1_6 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[6]/text()
  let $level1_7 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[7]/text()
  let $level1_8 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[8]/text()
  let $level1_9 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_1/p[9]/text()
  
  let $level2_1 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[1]/text()
  let $level2_2 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[2]/text()
  let $level2_3 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[3]/text()
  let $level2_4 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[4]/text()
  let $level2_5 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[5]/text()
  let $level2_6 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[6]/text()
  let $level2_7 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[7]/text()
  let $level2_8 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[8]/text()
  let $level2_9 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_2/p[9]/text()
  
  let $level3_1 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[1]/text()
  let $level3_2 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[2]/text()
  let $level3_3 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[3]/text()  
  let $level3_4 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[4]/text()
  let $level3_5 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[5]/text()
  let $level3_6 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[6]/text()  
  let $level3_7 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[7]/text()
  let $level3_8 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[8]/text()
  let $level3_9 :=  doc("book.xml")/book/body/item[$num]/contents/example/level_3/p[9]/text()  
  
(:Translation part========================================================:)
  let $t_level1_1 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[1]/text()
  let $t_level1_2 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[2]/text()
  let $t_level1_3 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[3]/text()
  let $t_level1_4 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[4]/text()
  let $t_level1_5 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[5]/text()
  let $t_level1_6 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[6]/text()
  let $t_level1_7 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[7]/text()
  let $t_level1_8 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[8]/text()
  let $t_level1_9 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_1/p[9]/text()
  
  let $t_level2_1 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[1]/text()
  let $t_level2_2 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[2]/text()
  let $t_level2_3 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[3]/text()
  let $t_level2_4 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[4]/text()
  let $t_level2_5 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[5]/text()
  let $t_level2_6 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[6]/text()
  let $t_level2_7 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[7]/text()
  let $t_level2_8 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[8]/text()
  let $t_level2_9 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_2/p[9]/text()
  
  let $t_level3_1 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[1]/text()
  let $t_level3_2 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[2]/text()
  let $t_level3_3 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[3]/text()  
  let $t_level3_4 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[4]/text()
  let $t_level3_5 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[5]/text()
  let $t_level3_6 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[6]/text()  
  let $t_level3_7 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[7]/text()
  let $t_level3_8 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[8]/text()
  let $t_level3_9 :=  doc("book.xml")/book/body/item[$num]/contents/translation/level_3/p[9]/text()
  
  
  (:Practice part========================================================:)
  
  let $p_1 :=  doc("book.xml")/book/body/item[$num]/contents/practice/p[1]/text()
  let $p_2 :=  doc("book.xml")/book/body/item[$num]/contents/practice/p[2]/text()
  let $p_3 :=  doc("book.xml")/book/body/item[$num]/contents/practice/p[3]/text()  
  let $p_4 :=  doc("book.xml")/book/body/item[$num]/contents/practice/p[4]/text()
  let $p_5 :=  doc("book.xml")/book/body/item[$num]/contents/practice/p[5]/text()
  let $p_6 :=  doc("book.xml")/book/body/item[$num]/contents/practice/p[6]/text()  
  let $p_7 :=  doc("book.xml")/book/body/item[$num]/contents/practice/p[7]/text()
  let $p_8 :=  doc("book.xml")/book/body/item[$num]/contents/practice/p[8]/text()
  let $p_9 :=  doc("book.xml")/book/body/item[$num]/contents/practice/p[9]/text()

 
  (:Practice answer part========================================================:)
  
  let $p_a_1 :=  doc("book.xml")/book/body/item[$num]/contents/answers/p[1]/text()
  let $p_a_2 :=  doc("book.xml")/book/body/item[$num]/contents/answers/p[2]/text()
  let $p_a_3 :=  doc("book.xml")/book/body/item[$num]/contents/answers/p[3]/text()  
  let $p_a_4 :=  doc("book.xml")/book/body/item[$num]/contents/answers/p[4]/text()
  let $p_a_5 :=  doc("book.xml")/book/body/item[$num]/contents/answers/p[5]/text()
  let $p_a_6 :=  doc("book.xml")/book/body/item[$num]/contents/answers/p[6]/text()  
  let $p_a_7 :=  doc("book.xml")/book/body/item[$num]/contents/answers/p[7]/text()
  let $p_a_8 :=  doc("book.xml")/book/body/item[$num]/contents/answers/p[8]/text()
  let $p_a_9 :=  doc("book.xml")/book/body/item[$num]/contents/answers/p[9]/text()
  
  

  (:Long Sentences part========================================================:)
  
  let $l_s_1 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[1]/text()
  let $l_s_2 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[2]/text()
  let $l_s_3 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[3]/text()  
  let $l_s_4 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[4]/text()
  let $l_s_5 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[5]/text()
  let $l_s_6 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[6]/text()  
  let $l_s_7 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[7]/text()
  let $l_s_8 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[8]/text()
  let $l_s_9 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences/p[9]/text()  
  
  

  (:Long Sentences Translation part========================================================:)
  
  let $t_l_s_1 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[1]/text()
  let $t_l_s_2 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[2]/text()
  let $t_l_s_3 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[3]/text()  
  let $t_l_s_4 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[4]/text()
  let $t_l_s_5 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[5]/text()
  let $t_l_s_6 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[6]/text()  
  let $t_l_s_7 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[7]/text()
  let $t_l_s_8 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[8]/text()
  let $t_l_s_9 :=  doc("book.xml")/book/body/item[$num]/contents/long-sentences-translation/p[9]/text()  

  return

  <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <title>Book Editor</title>
      <link rel="stylesheet" type="text/css" href="../static/style.css"/>
    </head>
    <body>
    <div class = "container">
      <div id="header"> <h1>Book Editor</h1>
      </div>
      <div class = "sidebar" id="left_side"></div>
      <div class = "sidebar" id="right_side">
        <button>button</button><br/><br/>
        <div><a href="http://localhost:8080/fop/fop?xml=/Program Files (x86)/BaseX/webapp/book.xml&amp;xslt=/Program Files (x86)/BaseX/webapp/book.xsl" target="_blank">fop</a></div>
        <button>button</button><br/><br/>
        <button>button</button><br/><br/>
        <button>button</button><br/><br/>
        <button>button</button><br/><br/>
        <button>button</button><br/><br/>
        <button>button</button><br/><br/>
      </div>
      <div id="content">
      
    <button ><a href="1">1</a></button>  
    <button ><a href="2">2</a></button>  
    <button ><a href="3">3</a></button>  
    <button ><a href="4">4</a></button>  
    <button ><a href="5">5</a></button>  
    <button ><a href="6">6</a></button>  
    <button ><a href="7">7</a></button>  
    <button ><a href="8">8</a></button>  
    <button ><a href="9">9</a></button>  
    <button ><a href="10">10</a></button>  
    <button ><a href="11">11</a></button>  
    <button ><a href="12">12</a></button>  
    <button ><a href="13">13</a></button>  
    <button ><a href="14">14</a></button>  
    <button ><a href="15">15</a></button>  
    <button ><a href="16">16</a></button>  
    <button ><a href="17">17</a></button>  
    <button ><a href="18">18</a></button>  
    <button ><a href="19">19</a></button>  
    <button ><a href="20">20</a></button>  
    <button ><a href="update/insert">insert</a></button>
    <button ><a href="#">update_all_n_c</a></button>
    <button ><a href="next">next_n_c</a></button>
    
    <form id = "sentence_form" method="post" action="sentences" target="_blank">
        <select name="tag">tag
        	<option>ing</option>
        	<option>ed</option>
        	<option>to</option>
        	<option>that</option>
        	<option>which</option>
        	<option>who</option>
        	<option>whose</option>
        	<option>whom</option>
        	<option>should</option>
        	<option>when</option>
        	<option>where</option>
        	<option>how</option>
        	<option>why</option>
        	<option>whoever</option>
        	<option>whatever</option>
        	<option>whenever</option>
        	<option>wherever</option>
        	<option>however</option>
        	<option>because</option>
        	<option>as soon as</option>
        </select>
        <input name = "num" type = "number" value="3"/>number<br/>
        <input type="submit" value = "sentences"/><br/><br/>
    </form>
    
    
     
      <h3>{$title}</h3>
  
    <h4> Basic Concept ------------------------------- </h4>

      <!---->
      <form method="post" action="form2/title/{$num}">
        <input name= "title" value ="{$title}"/><input type="submit" value = "title" /><br/><br/>
      </form>
      <form method="post" action="form2/before_start/{$num}">  
        <textarea name="before_start" rows="20" cols="90">{$before_start} </textarea><input type="submit" value = "before start" /></form><br/>
     
      <form method="post" action="form2/basic_concept/{$num}">
        <input name="basic_concept" value = "{$basic_concept}"/><input type="submit" value = "Basic Concept" /><br/><br/>
      </form>
      <form method="post" action="form2/mean/{$num}">  
        <textarea name="mean" rows="1" cols="90">{$mean} </textarea><input type="submit" value = "mean" /></form><br/>
      <form method="post" action="form2/form/{$num}">  
        <textarea name="structure" rows="1" cols="90">{$structure} </textarea><input type="submit" value = "form" /></form><br/>

      
        <form method="post" action="form2/ex/{$num}"><textarea name="ex" rows="1" cols="90">{$ex} </textarea><input type="submit" value = "ex" /></form><br/>
        <form method="post" action="form2/in_korean/{$num}"><textarea name="in_korean" rows="1" cols="90">{$in_korean} </textarea><input type="submit" value = "in_korean" /></form><br/>
        <form method="post" action="form2/in_sentence/{$num}"><textarea name="in_sentence" rows="1" cols="90">{$in_sentence} </textarea><input type="submit" value = "modify" /></form><br/>
        예문<br/>
        <form method="post" action="form2/ex_s1/{$num}"><textarea name="ex_s1" rows="1" cols="90">{$ex_s1} </textarea><input type="submit" value = "example" /></form><br/>
        <form method="post" action="form2/ex_s2/{$num}"><textarea name="ex_s2" rows="1" cols="90">{$ex_s2} </textarea><input type="submit" value = "example" /></form><br/>
        <form method="post" action="form2/ex_s3/{$num}"><textarea name="ex_s3" rows="1" cols="90">{$ex_s3} </textarea><input type="submit" value = "example" /></form><br/>
        <form method="post" action="form2/ex_s4/{$num}"><textarea name="ex_s4" rows="1" cols="90">{$ex_s4} </textarea><input type="submit" value = "example" /></form><br/><br/>
        
        
        <h2>문장이 길어지는 이유 </h2>
        <br/>
        <form method="post" action="form2/reason_longer/{$num}"><textarea name="reason_longer" rows="15" cols="90">{$reason_longer} </textarea><input type="submit" value = "modify" /></form><br/><br/>
        <h2>Explanation </h2>

       
        해설<br/>
        <form method="post" action="form2/explanation/{$num}"><textarea name="explanation" rows="20" cols="90">{$explanation}</textarea><input type="submit" value = "modify" /></form><br/>
        
      
        
        <button ><a href="#">Toggle</a></button>
        
        <h2>수준별 예문</h2>
        Level 1<br/>
        <form method="post" action="form2/level1_1/{$num}"><textarea name="level1_1" rows="1" cols="90">{$level1_1}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/level1_2/{$num}"><textarea name="level1_2" rows="1" cols="90">{$level1_2}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/level1_3/{$num}"><textarea name="level1_3" rows="1" cols="90">{$level1_3}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/level1_4/{$num}"><textarea name="level1_4" rows="1" cols="90">{$level1_4}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/level1_5/{$num}"><textarea name="level1_5" rows="1" cols="90">{$level1_5}</textarea><input type="submit" value = "modify" /></form><br/>
       
        
        Level2<br/>
        <form method="post" action="form2/level2_1/{$num}"><textarea name="level2_1" rows="2" cols="90">{$level2_1}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/level2_2/{$num}"><textarea name="level2_2" rows="2" cols="90">{$level2_2}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/level2_3/{$num}"><textarea name="level2_3" rows="2" cols="90">{$level2_3}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/level2_4/{$num}"><textarea name="level2_4" rows="2" cols="90">{$level2_4}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/level2_5/{$num}"><textarea name="level2_5" rows="2" cols="90">{$level2_5}</textarea><input type="submit" value = "modify" /></form><br/>
        
        
        Level3<br/>
        <form method="post" action="form2/level3_1/{$num}"><textarea name="level3_1" rows="1" cols="90">{$level3_1}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/level3_2/{$num}"><textarea name="level3_2" rows="1" cols="90">{$level3_2}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/level3_3/{$num}"><textarea name="level3_3" rows="1" cols="90">{$level3_3}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/level3_4/{$num}"><textarea name="level3_4" rows="1" cols="90">{$level3_4}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/level3_5/{$num}"><textarea name="level3_5" rows="1" cols="90">{$level3_5}</textarea><input type="submit" value = "modify" /></form><br/>
        
        
<h2> 수준별 예문 해석</h2>
        Level 1<br/>
        <form method="post" action="form2/t_level1_1/{$num}"><textarea name="t_level1_1" rows="1" cols="90">{$t_level1_1}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level1_2/{$num}"><textarea name="t_level1_2" rows="1" cols="90">{$t_level1_2}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level1_3/{$num}"><textarea name="t_level1_3" rows="1" cols="90">{$t_level1_3}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level1_4/{$num}"><textarea name="t_level1_4" rows="1" cols="90">{$t_level1_4}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level1_5/{$num}"><textarea name="t_level1_5" rows="1" cols="90">{$t_level1_5}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level1_6/{$num}"><textarea name="t_level1_6" rows="1" cols="90">{$t_level1_6}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level1_7/{$num}"><textarea name="t_level1_7" rows="1" cols="90">{$t_level1_7}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level1_8/{$num}"><textarea name="t_level1_8" rows="1" cols="90">{$t_level1_8}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level1_9/{$num}"><textarea name="t_level1_9" rows="1" cols="90">{$t_level1_9}</textarea><input type="submit" value = "modify" /></form><br/>
        
        Level2<br/>
        <form method="post" action="form2/t_level2_1/{$num}"><textarea name="t_level2_1" rows="1" cols="90">{$t_level2_1}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level2_2/{$num}"><textarea name="t_level2_2" rows="1" cols="90">{$t_level2_2}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level2_3/{$num}"><textarea name="t_level2_3" rows="1" cols="90">{$t_level2_3}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level2_4/{$num}"><textarea name="t_level2_4" rows="1" cols="90">{$t_level2_4}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level2_5/{$num}"><textarea name="t_level2_5" rows="1" cols="90">{$t_level2_5}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level2_6/{$num}"><textarea name="t_level2_6" rows="1" cols="90">{$t_level2_6}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level2_7/{$num}"><textarea name="t_level2_7" rows="1" cols="90">{$t_level2_7}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level2_8/{$num}"><textarea name="t_level2_8" rows="1" cols="90">{$t_level2_8}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level2_9/{$num}"><textarea name="t_level2_9" rows="1" cols="90">{$t_level2_9}</textarea><input type="submit" value = "modify" /></form><br/>
        
        Level3<br/>
        <form method="post" action="form2/t_level3_1/{$num}"><textarea name="t_level3_1" rows="1" cols="90">{$t_level3_1}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level3_2/{$num}"><textarea name="t_level3_2" rows="1" cols="90">{$t_level3_2}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level3_3/{$num}"><textarea name="t_level3_3" rows="1" cols="90">{$t_level3_3}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level3_4/{$num}"><textarea name="t_level3_4" rows="1" cols="90">{$t_level3_4}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level3_5/{$num}"><textarea name="t_level3_5" rows="1" cols="90">{$t_level3_5}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level3_6/{$num}"><textarea name="t_level3_6" rows="1" cols="90">{$t_level3_6}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level3_7/{$num}"><textarea name="t_level3_7" rows="1" cols="90">{$t_level3_7}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level3_8/{$num}"><textarea name="t_level3_8" rows="1" cols="90">{$t_level3_8}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_level3_9/{$num}"><textarea name="t_level3_9" rows="1" cols="90">{$t_level3_9}</textarea><input type="submit" value = "modify" /></form><br/>
        



    <h2>Pratice </h2>
        <form method="post" action="form2/p_1/{$num}"><textarea name="p_1" rows="10" cols="90">{$p_1}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/p_2/{$num}"><textarea name="p_2" rows="10" cols="90">{$p_2}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/p_3/{$num}"><textarea name="p_3" rows="10" cols="90">{$p_3}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/p_4/{$num}"><textarea name="p_4" rows="10" cols="90">{$p_4}</textarea><input type="submit" value = "modify" /></form><br/>
         
 
    <h2>연습문제 해답 </h2>
        <form method="post" action="form2/p_a_1/{$num}"><textarea name="p_a_1" rows="10" cols="90">{$p_a_1}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/p_a_2/{$num}"><textarea name="p_a_2" rows="10" cols="90">{$p_a_2}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/p_a_3/{$num}"><textarea name="p_a_3" rows="10" cols="90">{$p_a_3}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/p_a_4/{$num}"><textarea name="p_a_4" rows="10" cols="90">{$p_a_4}</textarea><input type="submit" value = "modify" /></form><br/>
        
    <h2>Long Sentences -------------------------------</h2>
        <form method="post" action="form2/l_s_1/{$num}"><textarea name="l_s_1" rows="1" cols="90">{$l_s_1}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/l_s_2/{$num}"><textarea name="l_s_2" rows="1" cols="90">{$l_s_2}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/l_s_3/{$num}"><textarea name="l_s_3" rows="1" cols="90">{$l_s_3}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/l_s_4/{$num}"><textarea name="l_s_4" rows="1" cols="90">{$l_s_4}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/l_s_5/{$num}"><textarea name="l_s_5" rows="1" cols="90">{$l_s_5}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/l_s_6/{$num}"><textarea name="l_s_6" rows="1" cols="90">{$l_s_6}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/l_s_7/{$num}"><textarea name="l_s_7" rows="1" cols="90">{$l_s_7}</textarea><input type="submit" value = "modify" /></form><br/>   
        <form method="post" action="form2/l_s_8/{$num}"><textarea name="l_s_8" rows="1" cols="90">{$l_s_8}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/l_s_9/{$num}"><textarea name="l_s_9" rows="1" cols="90">{$l_s_9}</textarea><input type="submit" value = "modify" /></form><br/>        
       
    <h2>장문 해석 -------------------------------</h2> 
        <form method="post" action="form2/t_l_s_1/{$num}"><textarea name="t_l_s_1" rows="1" cols="90">{$t_l_s_1}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_l_s_2/{$num}"><textarea name="t_l_s_2" rows="1" cols="90">{$t_l_s_2}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_l_s_3/{$num}"><textarea name="t_l_s_3" rows="1" cols="90">{$t_l_s_3}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_l_s_4/{$num}"><textarea name="t_l_s_4" rows="1" cols="90">{$t_l_s_4}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_l_s_5/{$num}"><textarea name="t_l_s_5" rows="1" cols="90">{$t_l_s_5}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_l_s_6/{$num}"><textarea name="t_l_s_6" rows="1" cols="90">{$t_l_s_6}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_l_s_7/{$num}"><textarea name="t_l_s_7" rows="1" cols="90">{$t_l_s_7}</textarea><input type="submit" value = "modify" /></form><br/>  
        <form method="post" action="form2/t_l_s_8/{$num}"><textarea name="t_l_s_8" rows="1" cols="90">{$t_l_s_8}</textarea><input type="submit" value = "modify" /></form><br/>
        <form method="post" action="form2/t_l_s_9/{$num}"><textarea name="t_l_s_9" rows="1" cols="90">{$t_l_s_9}</textarea><input type="submit" value = "modify" /></form><br/>        
       
        <br/>
        <input type="submit" value = "modify" />
        <input type="submit" value = "modify" />
        
        </div>
        <div id="bottom"></div>
        </div>
    </body>
  </html>
};




